### PR TITLE
Gseapy and verification

### PR DESCRIPTION
**Pull request by tmohoric**
Some major changes to the workflow: (1) Instead of EnrichR API the pathways are extracted with Python package gseapy. (2) Therefore previous stage 01 is split into three stages, one for download, one for processing and one for verification.

### CODE REVIEW

**Comment by zmughal** [comment]
Whenever I run, the `dvc repro` fails with:

```
[ERROR] Error fetching enrichment results: WikiPathway_2023_Human
```

which shouldn't fail as that is a valid gene set library.

Traceback:
```
Traceback (most recent call last):
  File "$HOME/sw_projects/biobricks-ai/eutoxrisk/eutoxrisk/stages/02_process.py", line 84, in <module>
    pathways = get_pathways_for_gene(gene_row['SYMBOL'], GENE_SET_LIBRARY)
  File "$HOME/sw_projects/biobricks-ai/eutoxrisk/eutoxrisk/stages/02_process.py", line 67, in get_pathways_for_gene
    enr = gp.enrich(gene_list=[gene_symbol],
  File "$HOME/.local/lib/python3.10/site-packages/gseapy/__init__.py", line 652, in enrich
    enr.run()
  File "$HOME/.local/lib/python3.10/site-packages/gseapy/enrichr.py", line 612, in run
    shortID, res = self.get_results(genes_list)
  File "$HOME/.local/lib/python3.10/site-packages/gseapy/enrichr.py", line 325, in get_results
    data = json.loads(response.text)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR: failed to reproduce 'process': failed to run: python3 stages/02_process.py, exited with 1
```

Do you know which version of `gseapy` you have?

**Comment by tmohoric** [comment]
Thanks for your email. I am using gseapy 1.1.3. Does it help?

V V sre., 9. okt. 2024 ob 23:55 je oseba Zaki Mughal [sivoais] <
***@***.***> napisala:

**Comment by zmughal** [comment]
Inside `02_process.py`, making the following change to find out which iteration is failing:

```python
    try:
        pathways = get_pathways_for_gene(gene_row['SYMBOL'], GENE_SET_LIBRARY)
        if isinstance(pathways, pd.DataFrame):
            if not pathways.empty:
                degs_pathways = pd.concat([degs_pathways, pathways], ignore_index=True)
    except:
        print(gene_row['SYMBOL'])
        breakpoint()
```

shows that it fails intermittently on different symbols each time. Probably a network issue? Either retry or look for a way to do everything entirely offline in one go?

**Comment by zmughal** [comment]
Merged via <https://github.com/biobricks-ai/eutoxrisk-temposeq/pull/8>, <https://github.com/biobricks-ai/eutoxrisk-temposeq/pull/9>.

**Pull request closed without merging**
